version: '3.8'

services:
  genhealth-api:
    build: .
    container_name: genhealth-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - MODEL_CACHE_DIR=/app/models
      - DATA_DIR=/app/data
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.0'
        reservations:
          memory: 4G
          cpus: '1.0'

  # Optional: Add Redis for caching
  redis:
    image: redis:7-alpine
    container_name: genhealth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: Add monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: genhealth-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

volumes:
  redis_data:
  prometheus_data:

networks:
  default:
    name: genhealth-network